#!/usr/bin/env bash

# Replace instances of EC2_PUBLIC_IP in the configuration file with EC2 public IP address.
grep -q EC2_PUBLIC_IP {{ pkg.svc_config_path }}/janus.cfg && sed -i "s/EC2_PUBLIC_IP/$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)/g" {{ pkg.svc_config_path }}/janus.cfg

# Replace instances of EC2_PRIVATE_IP in the configuration file with EC2 private IP address.
grep -q EC2_PRIVATE_IP {{ pkg.svc_config_path }}/janus.cfg && sed -i "s/EC2_PRIVATE_IP/$(curl -s http://169.254.169.254/latest/meta-data/private-ipv4)/g" {{ pkg.svc_config_path }}/janus.cfg
