#!/usr/bin/env bash

exec 2>&1

for f in {{ pkg.svc_config_path }}/*.cfg
do
  # Replace instances of EC2_PUBLIC_IP in the configuration file with EC2 public IP address.
  grep -q EC2_PUBLIC_IP $f && sed -i "s/EC2_PUBLIC_IP/$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)/g" $f

  # Replace instances of EC2_PRIVATE_IP in the configuration file with EC2 private IP address.
  grep -q EC2_PRIVATE_IP $f && sed -i "s/EC2_PRIVATE_IP/$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)/g" $f
done

exec janus --config={{ pkg.svc_config_path }}/janus.cfg --configs-folder={{ pkg.svc_config_path }} | logger
