#!/usr/bin/env bash

# Helper script that will check ec2 metadata for a peer in the same habitat
# ring based on tags, and echo "--peer IP" if peers present, empty string otherwise. 
#
# This script is meant to be run as an additional argument to hab sup run

INSTANCE_ID=$(curl -s "http://169.254.169.254/latest/meta-data/instance-id")
HAB_RING=$(aws ec2 --region us-west-1 describe-instances |  jq -r ".Reservations | map(.Instances) | flatten | .[] | select(.InstanceId == \"$INSTANCE_ID\") | .Tags | .[] | select(.Key == \"hab-ring\") | .Value ")
REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone | sed 's/[a-z]$//')
PRIVATE_IP=$(curl -s "http://169.254.169.254/latest/meta-data/local-ipv4")
PEER=$(aws ec2 --region $REGION describe-instances | jq -r ".Reservations | map(.Instances) | flatten | map(select(any(.Tags | from_entries ; .[\"hab-ring\"] == \"$HAB_RING\"))) | .[] | select(.State | .Code == 16) | .PrivateIpAddress" | grep -v $PRIVATE_IP | shuf | head -n1)

[[ ! -z "$PEER" ]] && echo "--peer $PEER"
