#!/usr/bin/env bash

# Helper script that will check ec2 metadata for a peer in the same IAM role as
# this box, and echo "--peer IP" if peers present, empty string otherwise. 
#
# This script is meant to be run as an additional argument to hab sup run

INSTANCE_PROFILE=$(curl -s "http://169.254.169.254/latest/meta-data/iam/info" | jq -r .InstanceProfileArn)
PRIVATE_IP=$(curl -s "http://169.254.169.254/latest/meta-data/local-ipv4")
REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone | sed 's/[a-z]$//')
PEER=$(aws ec2 --region $REGION describe-instances | jq -r ".Reservations | map(.Instances) | flatten | .[] | select(.IamInstanceProfile.Arn == \"$INSTANCE_PROFILE\") | .PrivateIpAddress" | grep -v $PRIVATE_IP | shuf | head -n1)

[[ ! -z "$PEERS" ]] && echo "--peer $PEER"

