#!{{pkgPathFor "core/bash"}}/bin/bash
exec 2>&1

service_group() {
  pkg_ident=$1
  hab svc status \
    | grep ${pkg_ident} \
    | grep -v "^package" \
    | awk '{print $7}'
  return $?
}

get_certificates() {
  # shellcheck disable=SC2154
  echo "$(date) Getting any needed LetsEncrypt certificates for '{{cfg.general.domain}}'"
  certbot certonly \
    --{{cfg.general.plugin}} \
    --config='{{pkg.svc_config_path}}/certbot.ini' \
    --noninteractive
  return $?
}

renew_certificates() {
  echo "$(date) Renewing LetsEncrypt certificates if neccessary"
  certbot renew \
    --{{cfg.general.plugin}} \
    --config='{{pkg.svc_config_path}}/certbot.ini'
  return $?
}

contains_pem() {
  local pem=$1
  local domain=$2
  grep '\-\-\-\-\-BEGIN ' "$pem" &> '/dev/null' \
    && grep '\-\-\-\-\-END ' "$pem" &> '/dev/null'
  return $?
}

get_certificates

while true
do
  renew_certificates
  sleep {{cfg.general.renewal_interval}}
done
