---

- block:
  - name: Include environment specific vars
    include_vars:
      file: "roles/farspark/vars/{{ env }}.yml"

  - name: Create work directory
    tempfile:
      state: directory
      suffix: deploy
    register: work_dir

  - name: Write Farspark config file
    template:
      src: farspark.toml.j2
      dest: "{{ work_dir.path }}/farspark.toml"

  - name: Write DD agent config file
    template:
      src: dd-agent.toml.j2
      dest: "{{ work_dir.path }}/dd-agent.toml"

  - name: Deploy Farspark configs
    shell: "cat {{ work_dir.path }}/farspark.toml | hab config apply --peer $(curl -s http://169.254.169.254/latest/meta-data/local-ipv4) --org mozillareality --ring mr farspark.default $(date +%s)"

  - name: Deploy Datadog Agent configs
    shell: "cat {{ work_dir.path }}/dd-agent.toml | hab config apply --peer $(curl -s http://169.254.169.254/latest/meta-data/local-ipv4) --org mozillareality --ring mr dd-agent.default $(date +%s)"

  always:
  - name: Remove work directory
    file:
      path: "{{ work_dir.path }}"
      state: absent
