name: compare branches
on:
  workflow_call:
   inputs:
    main:
     description:  "Main Branch"
     required: true
     type: string
    releasing:
      description: "releasing Branch"
      required: true
      type: string


jobs:
  compare:
    runs-on: ubuntu-latest
    outputs:
      diff: ${{steps.compare.outputs.diff}}
    steps:
      - uses: actions/checkout@v2
      - run: | 
          if [ "$(git rev-parse ${{inputs.releasing}})" != "$(git rev-parse ${{inputs.main}})" ] then 
          echo  "Different"
          else 
          echo "Same"
          exit
          fi


