name: compare branches
on:
  workflow_call:
   inputs:
    main:
     description:  "Main Branch"
     required: true
     type: string
    releasing:
      description: "releasing Branch"
      required: true
      type: string


jobs:
  compare:
    runs-on: ubuntu-latest
    outputs:
      diff: ${{steps.compare.outputs.diff}}
    steps:
      - uses: actions/checkout@v2
      - run:  bash .github/workflows/compare.sh

