name: compare branches
on:
  workflow_call:
   inputs:
    main:
     description:  "Main Branch"
     required: true
     type: string
    releasing:
      description: "releasing Branch"
      required: true
      type: string


jobs:
  compare:
    runs-on: ubuntu-latest
    outputs:
      diff: ${{steps.compare.outputs.diff}}
    steps:
      - uses: actions/checkout@v2
      - run: | 
          if [ "$(git rev-parse ${{inputs.releasing}})" != "$(git rev-parse ${{inputs.main}})" ]; then 
          echo "Branches are different launching package release" 
          echo '::set-output name=diff::launch'
          else 
          echo "Same"
          exit
          fi
  launch:
    needs: compare
    if: ${{needs.compare.outputs.diff}} == 'launch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: | 
          echo "Starting Release Process"



